In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("iris.csv")
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
print(df.shape)
print(df.columns)
print(df.head())

(150, 5)
Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='str')
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [5]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
print("Mean:")
print(df["sepal.length"].mean())
print(df["sepal.width"].mean())
print(df["petal.length"].mean())
print(df["petal.width"].mean())

Mean:
5.843333333333334
3.0573333333333337
3.7580000000000005
1.1993333333333336

In [7]:
print("Standard Deviation:")
print(df["sepal.length"].std())
print(df["sepal.width"].std())
print(df["petal.length"].std())
print(df["petal.width"].std())

Standard Deviation:
0.828066127977863
0.4358662849366982
1.7652982332594662
0.7622376689603465

In [8]:
print("Covariance:")
print("1 & 2:", df["sepal.length"].cov(df["sepal.width"]))
print("1 & 3:", df["sepal.length"].cov(df["petal.length"]))
print("1 & 4:", df["sepal.length"].cov(df["petal.width"]))

Covariance:
1 & 2: -0.0424340044742729
1 & 3: 1.2743154362416107
1 & 4: 0.5162706935123041

In [9]:
print("Correlation:")
print("1 & 2:", df["sepal.length"].corr(df["sepal.width"]))
print("1 & 3:", df["sepal.length"].corr(df["petal.length"]))
print("1 & 4:", df["sepal.length"].corr(df["petal.width"]))

Correlation:
1 & 2: -0.11756978413300198
1 & 3: 0.8717537758865831
1 & 4: 0.8179411262715757